build:
	@echo "Making Build"

check-install:
	@echo "Checking intalation..."

install:
	@echo "Instaling software"

clean:
	@echo "Clean"
	
test:
	@echo "Run All Tests"

composer:
	@echo "Run All Composer Dependencies"

doc:
	@echo "Run PHPDocumentor"

coverage:
	@echo "Run Coverage Tests"

.PHONY: test clean